import pandas as pd

def engineer_features(input_file='synthetic_energy_data.csv', output_file='energy_features.csv'):
    """
    Loads synthetic energy data, engineers datetime and lag features, and saves the output.
    """
    print(f"Loading data from {input_file}...")
    df = pd.read_csv(input_file)
    
    # Optional: ensure timestamp is datetime object
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # 1. Extract datetime features
    print("Extracting datetime features...")
    df['hour'] = df['timestamp'].dt.hour
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    
    # 2. Create lag features for energy_consumption
    print("Creating lag features...")
    # Previous hour (t-1)
    df['energy_lag_1h'] = df['energy_consumption'].shift(1)
    # Previous day (t-24) - assumes data is perfectly sorted and hourly
    df['energy_lag_24h'] = df['energy_consumption'].shift(24)
    
    # 3. Drop null values generated by the shifting process
    initial_shape = df.shape
    df.dropna(inplace=True)
    print(f"Dropped {initial_shape[0] - df.shape[0]} rows containing null values due to lagging.")
    
    # 4. Save to CSV
    df.to_csv(output_file, index=False)
    print(f"Feature engineering complete. Data shape: {df.shape}")
    print(f"Saved extracted features to '{output_file}'.")

if __name__ == "__main__":
    engineer_features()
